resources:
  - ./all.yaml

secretGenerator:
  - name: nginx
    envs:
      - "config/secrets.env"
    type: Opaque
configMapGenerator:
  - name: nginx
    envs:
      - "config/configmaps.env"

generatorOptions:
  disableNameSuffixHash: true
