apiVersion: apps/v1
kind: Deployment
metadata:
  name: vueapp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vueapp
  template:
    metadata:
      labels:
        app: vueapp
    spec:
      containers:
      - image: docker.io/kittinanchanpreecha/vuejs-practice:1.0.0
        name: vueapp
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: '50Mi'
            cpu: '50m'
          limits:
            memory: '50Mi'
            cpu: '50m'
        securityContext:
          privileged: false
          #readOnlyRootFilesystem: false # guestbook neet to write to /var/run/apache2/apache2.pid
          allowPrivilegeEscalation: false