apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiapp-deployment
  namespace: team-riker
spec:
  selector:
    matchLabels:
      app: skiapp
  replicas: 2 
  template: 
    metadata:
      labels:
        app: skiapp
    spec:
      containers:
      - name: vueapp
        image: docker.io/kittinanchanpreecha/vuejs-practice:1.0.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"