apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: vueapp-rollout
  namespace: team-riker
  labels:
    app: vueapp
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: vueapp
  template:
    metadata:
      labels:
        app: vueapp
    spec:
      containers:
      - name: vueapp
        image: docker.io/kittinanchanpreecha/vuejs-practice:1.0.2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "1"
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: vueapp-service
      previewService: vueapp-service-preview
---

apiVersion: v1
kind: Service
metadata:
  name: vueapp-service-preview
  namespace: team-riker
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: vueapp

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vueapp-ingress-preview
  namespace: team-riker
  annotations:
    alb.ingress.kubernetes.io/group.name: riker-preview
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #alb.ingress.kubernetes.io/tags: Environment=preview,Team=RikerPreview
spec:
  ingressClassName: alb
  rules:
  - host: #vueapprev.{{ .Values.spec.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vueapp-service-preview
            port: 
              number: 80
